title: "Imagination running low"
description: "Notes & experiments"
theme: minima

header_pages:
  - blog.md
  - about.md
  - cv.md


  
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num"
